# SPDX-License-Identifier: GPL-2.0
vfio-platform-base-y := vfio_platform_common.o vfio_platform_irq.o
obj-$(CPTCFG_VFIO_PLATFORM_BASE) += vfio-platform-base.o
obj-$(CPTCFG_VFIO_PLATFORM_BASE) += reset/

vfio-platform-y := vfio_platform.o
obj-$(CPTCFG_VFIO_PLATFORM) += vfio-platform.o

vfio-amba-y := vfio_amba.o
obj-$(CPTCFG_VFIO_AMBA) += vfio-amba.o
