#!/bin/sh
#
# Creates a dkms.conf file

PKG_NAME="intel-xe-dkms"
PKG_VER="1.0"
REL_NAME="1"
REL_TYPE=""
BUILD_TYPE=""
XE_CONFIG="xe"

helpFunction()
{
	echo ""
	echo "Usage: $0 -n packagename -v packageversion -r releaseversion -s buildversion"
	echo -e "\t-n packagename"
	echo -e "\t-v packageversion"
	echo -e "\t-r releaseversion"
	echo -e "\t-s buildversion"
	exit 1
}

while getopts "n:v:r:s:" opt
do
	case "$opt" in
		n ) PKG_NAME="$OPTARG" ;;
		v ) PKG_VER="$OPTARG" ;;
		r ) REL_NAME="$OPTARG" ;;
		s ) BUILD_TYPE="$OPTARG" ;;
		? ) helpFunction ;;
	esac
done

# Control below line by conditionally adding DEL at the beginning of line
# those lines will be disabled by sed
#
sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	PACKAGE_NAME="$PKG_NAME"
	PACKAGE_VERSION="$PKG_VER-$REL_NAME"
	AUTOINSTALL="yes"

	BUILT_MODULE_NAME[0]="xe-compat"
	BUILT_MODULE_LOCATION[0]="src/compat"
	DEST_MODULE_LOCATION[0]="/updates"

	BUILT_MODULE_NAME[1]="xe"
	BUILT_MODULE_LOCATION[1]="src/drivers/gpu/drm/xe"
	DEST_MODULE_LOCATION[1]="/updates"

	BUILT_MODULE_NAME[2]="ttm"
	BUILT_MODULE_LOCATION[2]="src/drivers/gpu/drm/ttm"
        DEST_MODULE_LOCATION[2]="/updates"

	BUILT_MODULE_NAME[3]="drm_ttm_helper"
	BUILT_MODULE_LOCATION[3]="src"
	DEST_MODULE_LOCATION[3]="/updates"

	BUILT_MODULE_NAME[4]="gpu-sched"
	BUILT_MODULE_LOCATION[4]="src/drivers/gpu/drm/scheduler"
	DEST_MODULE_LOCATION[4]="/updates"

	BUILT_MODULE_NAME[5]="intel-vsec"
	BUILT_MODULE_LOCATION[5]="src/drivers/platform/x86/intel"
	DEST_MODULE_LOCATION[5]="/updates"

	BUILT_MODULE_NAME[6]="pmt_class"
	BUILT_MODULE_LOCATION[6]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[6]="/updates"

	BUILT_MODULE_NAME[7]="pmt_telemetry"
	BUILT_MODULE_LOCATION[7]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[7]="/updates"

	BUILT_MODULE_NAME[8]="pmt_crashlog"
	BUILT_MODULE_LOCATION[8]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[8]="/updates"

	BUILT_MODULE_NAME[9]="pmt_discovery"
	BUILT_MODULE_LOCATION[9]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[9]="/updates"

	BUILT_MODULE_NAME[10]="mtd_intel_dg"
	BUILT_MODULE_LOCATION[10]="src"
	DEST_MODULE_LOCATION[10]="/updates"
	
	BUILT_MODULE_NAME[11]="mei"
        BUILT_MODULE_LOCATION[11]="src/drivers/misc/mei"
        DEST_MODULE_LOCATION[11]="/updates"

        BUILT_MODULE_NAME[12]="mei-me"
        BUILT_MODULE_LOCATION[12]="src/drivers/misc/mei"
        DEST_MODULE_LOCATION[12]="/updates"

        BUILT_MODULE_NAME[13]="mei-gsc"
        BUILT_MODULE_LOCATION[13]="src/drivers/misc/mei"
        DEST_MODULE_LOCATION[13]="/updates"

        BUILT_MODULE_NAME[14]="mei-txe"
        BUILT_MODULE_LOCATION[14]="src/drivers/misc/mei"
        DEST_MODULE_LOCATION[14]="/updates"

        BUILT_MODULE_NAME[15]="mei_hdcp"
        BUILT_MODULE_LOCATION[15]="src/drivers/misc/mei/hdcp"
        DEST_MODULE_LOCATION[15]="/updates"

        BUILT_MODULE_NAME[16]="mei_pxp"
        BUILT_MODULE_LOCATION[16]="src/drivers/misc/mei/pxp"
        DEST_MODULE_LOCATION[16]="/updates"

        BUILT_MODULE_NAME[17]="mei_gsc_proxy"
        BUILT_MODULE_LOCATION[17]="src/drivers/misc/mei/gsc_proxy"
        DEST_MODULE_LOCATION[17]="/updates"

        BUILT_MODULE_NAME[18]="mei_lb"
        BUILT_MODULE_LOCATION[18]="src/drivers/misc/mei"
        DEST_MODULE_LOCATION[18]="/updates"

        BUILT_MODULE_NAME[19]="mei-vsc"
        BUILT_MODULE_LOCATION[19]="src/drivers/misc/mei"
        DEST_MODULE_LOCATION[19]="/updates"

        BUILT_MODULE_NAME[20]="mei-vsc-hw"
        BUILT_MODULE_LOCATION[20]="src/drivers/misc/mei"
        DEST_MODULE_LOCATION[20]="/updates"

	i=21

	select_build_full_vfio() {
		if [ -z "\$kernelver" ]; then
			echo "false"
			return
		fi
		kver_major=\$(echo "\$kernelver" | cut -d. -f1)
		kver_minor=\$(echo "\$kernelver" | cut -d. -f2)
		if [ "\$kver_major" -lt 6 ] || { [ "\$kver_major" -eq 6 ] && [ "\$kver_minor" -lt 2 ]; }; then
			echo "true"
		else
			echo "false"
		fi
	}

	if [ "\$(select_build_full_vfio)" = "true" ]; then
		BUILT_MODULE_NAME[\$i]="vfio"
		BUILT_MODULE_LOCATION[\$i]="src/drivers/vfio"
		DEST_MODULE_LOCATION[\$i]="/updates"
		i=\$((i + 1))

		BUILT_MODULE_NAME[\$i]="vfio_iommu_type1"
		BUILT_MODULE_LOCATION[\$i]="src/drivers/vfio"
		DEST_MODULE_LOCATION[\$i]="/updates"
		i=\$((i + 1))

		BUILT_MODULE_NAME[\$i]="vfio-pci-core"
		BUILT_MODULE_LOCATION[\$i]="src/drivers/vfio/pci"
		DEST_MODULE_LOCATION[\$i]="/updates"
		i=\$((i + 1))
	fi

	BUILT_MODULE_NAME[\$i]="xe-vfio-pci"
	BUILT_MODULE_LOCATION[\$i]="src/drivers/vfio/pci/xe"
	DEST_MODULE_LOCATION[\$i]="/updates"
	i=\$((i + 1))

	select_drm_gpuvm() {
		if [ -z "\$kernelver" ]; then
			echo "false"
			return
		fi
		kver_short=\$(echo "\$kernelver" | cut -d. -f1,2)
		case "\$kver_short" in
			5.15|6.6|6.7) echo "true" ;;
			*) echo "false" ;;
		esac
	}

	select_xe_515_extra_modules() {
		if [ -z "\$kernelver" ]; then
			echo "false"
			return
		fi
		kver_short=\$(echo "\$kernelver" | cut -d. -f1,2)
		case "\$kver_short" in
			5.15) echo "true" ;;
			*) echo "false" ;;
		esac
	}

	BUILT_MODULE_NAME[i]="drm_gpusvm_helper"
	BUILT_MODULE_LOCATION[i]="src"
	DEST_MODULE_LOCATION[i]="/updates"
	i=\$((i + 1))

	if [ "\$(select_drm_gpuvm)" = "true" ]; then
		BUILT_MODULE_NAME[i]="drm_gpuvm"
		BUILT_MODULE_LOCATION[i]="src"
		DEST_MODULE_LOCATION[i]="/updates"
		i=\$((i + 1))
	fi

	if [ "\$(select_xe_515_extra_modules)" = "true" ]; then
		BUILT_MODULE_NAME[\$i]="drm_exec"
		BUILT_MODULE_LOCATION[\$i]="src"
		DEST_MODULE_LOCATION[\$i]="/updates"
		i=\$((i + 1))

		BUILT_MODULE_NAME[\$i]="drm_buddy"
		BUILT_MODULE_LOCATION[\$i]="src"
		DEST_MODULE_LOCATION[\$i]="/updates"
		i=\$((i + 1))

		BUILT_MODULE_NAME[\$i]="drm_suballoc_helper"
		BUILT_MODULE_LOCATION[\$i]="src"
		DEST_MODULE_LOCATION[\$i]="/updates"
		i=\$((i + 1))
	fi

	# Find out how many CPU cores can be use if we pass appropriate -j option to make.
	# DKMS could use all cores on multicore systems to build the kernel module.
	num_cpu_cores()
	{
		if [ -x /usr/bin/nproc ]; then
			np=`nproc`
			if [ "\$np" -le "64" ]; then
				echo "\$np"
			else
				echo "64"
			fi
		else
			echo "1"
		fi
	}

	MAKE="export LEX=flex; export YACC=bison; pwd; autoreconf --install; autoconf ; autoheader ;automake --add-missing ;./configure --enable-linux-builtin --with-linux=/lib/modules/\$kernelver/build; cp src/defconfigs/$XE_CONFIG src/.config ; make olddefconfig; make -j\$(num_cpu_cores) modules"
	CLEAN="export LEX=flex; export YACC=bison; 'make' mrproper"
EOF
