#!/bin/sh
set -e
# Automatically added by dh_dkms/3.0.11-1ubuntu13
# The original file can be found in template-dkms-mkdeb/debian/postinst
# in the DKMS tarball, check it for copyright notices.

DKMS_NAME=intel-xe-dkms
DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
DKMS_VERSION=6.14.0.37+6.17.13.62.260409.10

postinst_found=0

case "$1" in
	configure)
		for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
			if [ -f $DKMS_POSTINST ]; then
				$DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
				postinst_found=1
				break
			fi
		done
		if [ "$postinst_found" -eq 0 ]; then
			echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
			echo "built with legacy DKMS support."
			echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
			echo "support or upgrade DKMS to a more current version."
			exit 1
		fi
	;;
esac
# End automatically added section
#
#postinst script for intel-xe-dkms

set -e

#update initramfs
case "$1" in
    configure)
	depmod -a
	if [ -x /usr/sbin/update-initramfs ]; then
	    /usr/sbin/update-initramfs -u
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

exit 0
