#!/bin/sh
#
# Creates a dkms.conf file for RPM DKMS package
#

PKG_NAME="intel-xe-dkms"
PKG_VER="1.0"
REL_NAME="1"
BUILD_TYPE=""

helpFunction()
{
	echo ""
	echo "Usage: $0 -n packagename -v packageversion -r releaseversion -s buildversion"
	echo -e "\t-n packagename"
	echo -e "\t-v packageversion"
	echo -e "\t-r releaseversion"
	echo -e "\t-s buildversion"
	exit 1
}

while getopts "n:v:r:s:" opt
do
	case "$opt" in
		n ) PKG_NAME="$OPTARG" ;;
		v ) PKG_VER="$OPTARG" ;;
		r ) REL_NAME="$OPTARG" ;;
		s ) BUILD_TYPE="$OPTARG" ;;
		? ) helpFunction ;;
	esac
done

# Control below line by conditionally adding DEL at the beginning of line
# those lines will be disabled by sed
#
sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	PACKAGE_NAME="$PKG_NAME"
	PACKAGE_VERSION="$PKG_VER"
	AUTOINSTALL="yes"

	MAKE="export LEX=flex; export YACC=bison; KSRC=/usr/src/kernels/\\\$kernelver; if [ ! -d \\\$KSRC ]; then KSRC=/lib/modules/\\\$kernelver/build; fi; ./compile.sh compile \\\$KSRC"

	CLEAN="export LEX=flex; export YACC=bison; 'make' -C src clean 2>/dev/null || true; 'make' mrproper 2>/dev/null || true"

	BUILT_MODULE_NAME[0]="xe-compat"
	BUILT_MODULE_LOCATION[0]="src/compat"
	DEST_MODULE_LOCATION[0]="/updates"

	BUILT_MODULE_NAME[1]="xe"
	BUILT_MODULE_LOCATION[1]="src/drivers/gpu/drm/xe"
	DEST_MODULE_LOCATION[1]="/updates"

	BUILT_MODULE_NAME[2]="ttm"
	BUILT_MODULE_LOCATION[2]="src/drivers/gpu/drm/ttm"
	DEST_MODULE_LOCATION[2]="/updates"

	BUILT_MODULE_NAME[3]="drm_ttm_helper"
	BUILT_MODULE_LOCATION[3]="src"
	DEST_MODULE_LOCATION[3]="/updates"

	BUILT_MODULE_NAME[4]="gpu-sched"
	BUILT_MODULE_LOCATION[4]="src/drivers/gpu/drm/scheduler"
	DEST_MODULE_LOCATION[4]="/updates"

	BUILT_MODULE_NAME[5]="intel-vsec"
	BUILT_MODULE_LOCATION[5]="src/drivers/platform/x86/intel"
	DEST_MODULE_LOCATION[5]="/updates"

	BUILT_MODULE_NAME[6]="pmt_class"
	BUILT_MODULE_LOCATION[6]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[6]="/updates"

	BUILT_MODULE_NAME[7]="pmt_telemetry"
	BUILT_MODULE_LOCATION[7]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[7]="/updates"

	BUILT_MODULE_NAME[8]="pmt_crashlog"
	BUILT_MODULE_LOCATION[8]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[8]="/updates"

	BUILT_MODULE_NAME[9]="pmt_discovery"
	BUILT_MODULE_LOCATION[9]="src/drivers/platform/x86/intel/pmt"
	DEST_MODULE_LOCATION[9]="/updates"

	BUILT_MODULE_NAME[10]="mtd_intel_dg"
	BUILT_MODULE_LOCATION[10]="src"
	DEST_MODULE_LOCATION[10]="/updates"

	BUILT_MODULE_NAME[11]="mei"
	BUILT_MODULE_LOCATION[11]="src/drivers/misc/mei"
	DEST_MODULE_LOCATION[11]="/updates"

	BUILT_MODULE_NAME[12]="mei-me"
	BUILT_MODULE_LOCATION[12]="src/drivers/misc/mei"
	DEST_MODULE_LOCATION[12]="/updates"

	BUILT_MODULE_NAME[13]="mei-gsc"
	BUILT_MODULE_LOCATION[13]="src/drivers/misc/mei"
	DEST_MODULE_LOCATION[13]="/updates"

	BUILT_MODULE_NAME[14]="mei-txe"
	BUILT_MODULE_LOCATION[14]="src/drivers/misc/mei"
	DEST_MODULE_LOCATION[14]="/updates"

	BUILT_MODULE_NAME[15]="mei_hdcp"
	BUILT_MODULE_LOCATION[15]="src/drivers/misc/mei/hdcp"
	DEST_MODULE_LOCATION[15]="/updates"

	BUILT_MODULE_NAME[16]="mei_pxp"
	BUILT_MODULE_LOCATION[16]="src/drivers/misc/mei/pxp"
	DEST_MODULE_LOCATION[16]="/updates"

	BUILT_MODULE_NAME[17]="mei_gsc_proxy"
	BUILT_MODULE_LOCATION[17]="src/drivers/misc/mei/gsc_proxy"
	DEST_MODULE_LOCATION[17]="/updates"

	BUILT_MODULE_NAME[18]="mei_lb"
	BUILT_MODULE_LOCATION[18]="src/drivers/misc/mei"
	DEST_MODULE_LOCATION[18]="/updates"

	BUILT_MODULE_NAME[19]="mei-vsc"
	BUILT_MODULE_LOCATION[19]="src/drivers/misc/mei"
	DEST_MODULE_LOCATION[19]="/updates"

	BUILT_MODULE_NAME[20]="mei-vsc-hw"
	BUILT_MODULE_LOCATION[20]="src/drivers/misc/mei"
	DEST_MODULE_LOCATION[20]="/updates"
EOF
