AC_DEFUN([AC_XE_CONFIG], [
	AC_ARG_ENABLE([linux-builtin],
		[AS_HELP_STRING([--enable-linux-builtin],
		[Configure for builtin kernel modules @<:@default=no@:>@])],
		[],
		[enable_linux_builtin=no])
	AC_CONFIG_KERNEL
	AC_DMA_FENCE_ARRAY_ALLOC_NOT_PRESENT
	AC_STRSCPY_ARG3_PRESENT
	AC_STR_PLURAL_NOT_PRESENT
	AC_PM_RUNTIME_GET_IF_ACTIVE_ARG2_NOT_PRESENT
	AC_COREDUMPM_TIMEOUT_NOT_PRESENT
	AC_DEVCOREDUMP_PUT_NOT_PRESENT
	AC_DRM_BUDDY_FREE_LIST_ARG3_NOT_PRESENT
	AC_DRM_DBG_PRINTER_NOT_PRESENT
	AC_DRM_BUDDY_BLOCK_TRIM_2ND_ARG_NOT_PRESENT
	AC_STR_UP_DOWN_NOT_PRESENT
	AC_FOP_UNSIGNED_OFFSET_NOT_PRESENT
	AC_DRM_LINE_PRINTER_NOT_PRESENT
	AC_STRUCT_DRM_PRINTER_ORIGIN_NOT_PRESENT
	AC_DRM_DBG_RATELIMITED_NOT_PRESENT
	AC_SHRINKER_ALLOC_NOT_PRESENT
	AC_DRM_EXEC_INIT_ARG3_NOT_PRESENT
	AC_SECS_TO_JIFFIES_NOT_PRESENT
	AC_DRMM_CGROUP_REGISTER_REGION_NOT_PRESENT
	AC_PMU_SCOPE_MEMBER_NOT_PRESENT
	AC_PCI_IOV_VF_BAR_FUNCTIONS_NOT_PRESENT
	AC_DRM_GPUVM_RENAMING_SYMBOLS
	AC_DRV_DATE_NOT_PRESENT
	AC_ALLOC_ORDERED_WORKQUEUE_LOCKDEP_MAP_NOT_PRESENT
	AC_CONST_STRUCT_BIN_ATTRIBUTE_IS_NOT_PRESENT
	AC_STRUCT_BIN_ATTRIBUTE_READ_NEW_NOT_PRESENT
	AC_MODULE_IMPORT_TO_STRING_LITERAL_PRESENT
	AC_SHMEM_WRITEOUT_NOT_PRESENT
	AC_KMAP_LOCAL_PAGE_TRY_FROM_PANIC_NOT_PRESENT
	AC_GENMASK_U32_NOT_PRESENT
	AC_DRM_DEV_WEDGED_EVENT_NOT_PRESENT
	AC_DRM_FENCE_IS_LATER_ARG_DMA_FENCE_OPS_NOT_PRESENT
	AC_DRMM_WORKQUEUE_RELEASE_NOT_PRESENT
	AC_DIV_U64_ROUND_UP_NOT_PRESENT
	AC_DRM_GPUVA_OP_DRIVER_NOT_PRESENT
	AC_HRTIMER_SETUP_NOT_PRESENT
	AC_STRUCT_CTL_TABLE_CONST_KEYWORD_NOT_PRESENT
	AC_PM_SUSPEND_IN_PROGRESS_NOT_PRESENT
	AC_DRM_COREDUMP_PRINTER_IS_FULL_NOT_PRESENT
	AC_DISBALE_WORK_SYNC_NOT_PRESENT
	AC_ACCESS_REMOTE_VM_NOT_PRESENT
	AC_DEFINE_SYSFS_GROUP_VISIBLE_NOT_PRESENT
	AC_DRMM_ALLOC_ORDERED_WORKQUEUE_NOT_PRESENT
	AC_DRM_WEDGE_RECOVERY_VENDOR_NOT_PRESENT
	AC_DRM_PRINT_HEX_DUMP_NOT_PRESENT
	AC_MATCH_TOKEN_UUID_NOT_PRESENT
	AC_EXPORT_SYMBOL_FOR_MODULES_NOT_PRESENT
	AC_DRM_MINOR_DEBUGFS_SYMLINK_NOT_PRESENT
	AC_FREE_ATTRIBUTE_NOT_PRESENT
	AC_DRM_DEV_WEDGED_EVENT_ARG3_NOT_PRESENT
	AC_OBJTOOL_COPY_ATTRIBUTE_NEEDED
	AC_DMA_RESV_USAGE_NOT_PRESENT
	AC_DMA_RESV_FOR_EACH_FENCE_NOT_PRESENT
	AC_VM_FLAGS_SET_NOT_PRESENT
	AC_DMA_FENCE_SET_DEADLINE_NOT_PRESENT
	AC_DMA_RESV_RESERVE_FENCES_NOT_PRESENT
	AC_DMA_RESV_ADD_FENCE_NOT_PRESENT
	AC_FOLIO_PUT_NOT_PRESENT
	AC_FOLIO_FILE_PAGE_NOT_PRESENT
	AC_FOLIO_MARK_ACCESSED_NOT_PRESENT
	AC_FOLIO_LOCK_NOT_PRESENT
	AC_FOLIO_UNLOCK_NOT_PRESENT
	AC_FOLIO_MARK_DIRTY_NOT_PRESENT
	AC_FOLIO_MAPPED_NOT_PRESENT
	AC_FOLIO_CLEAR_DIRTY_FOR_IO_NOT_PRESENT
	AC_FOLIO_SET_RECLAIM_NOT_PRESENT
	AC_FOLIO_CLEAR_RECLAIM_NOT_PRESENT
	AC_FOLIO_TEST_WRITEBACK_NOT_PRESENT
	AC_SHMEM_READ_FOLIO_NOT_PRESENT
	AC_SHMEM_READ_FOLIO_GFP_NOT_PRESENT
	AC_DMA_FENCE_IS_CONTAINER_NOT_PRESENT
	AC_COUNTED_BY_NOT_PRESENT
	AC_REGISTER_SHRINKER_ARG2_NOT_PRESENT
	AC_DRMM_MUTEX_INIT_NOT_PRESENT
	AC_DRM_SHOW_FDINFO_NOT_PRESENT
	AC_DRM_MEMORY_STATS_NOT_PRESENT
	AC_FOR_EACH_OR_BIT_NOT_PRESENT
	AC_FIELD_PREP_CONST_NOT_PRESENT
	AC_GENERIC_HANDLE_IRQ_SAFE_NOT_PRESENT

dnl # Macros to check for header availability
	AC_KERNEL_CHECK_HEADERS([drm/i915_gsc_proxy_mei_interface.h])
	AC_KERNEL_CHECK_HEADERS([drm/intel/i915_drm.h])
	AC_KERNEL_CHECK_HEADERS([linux/wordpart.h])
	AC_KERNEL_CHECK_HEADERS([linux/workqueue_types.h])
	dnl # v6.8-d84f31791517 locking/mutex: split out mutex_types.h
	AC_KERNEL_CHECK_HEADERS([linux/mutex_types.h])
	dnl # v5.18-7938f4218168 dma-buf-map: Rename to iosys-map
	AC_KERNEL_CHECK_HEADERS([linux/iosys-map.h])
	dnl # v6.6-e6303f323b1a drm: manager to keep track of GPUs VA mappings
	AC_KERNEL_CHECK_HEADERS([drm/drm_gpuva_mgr.h])
	dnl # v5.16-d2a8ebbf8192 kernel.h: split out container_of() and typeof_member() macros
	AC_KERNEL_CHECK_HEADERS([linux/container_of.h])
	dnl # v6.1-9a3bab6af4c8 locking: Introduce __cleanup() macro infrastructure
        AC_KERNEL_CHECK_HEADERS([linux/cleanup.h])
	dnl # v6.6-b229baa374db kernel.h: split out COUNT_ARGS() and CONCATENATE() to args.h
	AC_KERNEL_CHECK_HEADERS([linux/args.h])
	dnl # v6.3-e047c5eaa763 kunit: Expose 'static stub' API to redirect functions
	AC_KERNEL_CHECK_HEADERS([kunit/static_stub.h])
	dnl $ v6.5-fca76071bab2 lib/string_helpers: Split out string_choices.h
	AC_KERNEL_CHECK_HEADERS([linux/string_choices.h])
	AC_KERNEL_CHECK_HEADERS([drm/intel/i915_gsc_proxy_mei_interface.h])
	dnl # v5.19-1e3dc1d8622b drm/i915/gsc: add gsc as a mei auxiliary device
	AC_KERNEL_CHECK_HEADERS([linux/mei_aux.h])

	AC_KERNEL_WAIT
])
