AC_DEFUN([AC_XE_CONFIG], [
	AC_ARG_ENABLE([linux-builtin],
		[AS_HELP_STRING([--enable-linux-builtin],
		[Configure for builtin kernel modules @<:@default=no@:>@])],
		[],
		[enable_linux_builtin=no])
	AC_CONFIG_KERNEL
	AC_DMA_FENCE_ARRAY_ALLOC_NOT_PRESENT
	AC_STRSCPY_ARG3_PRESENT
	AC_STR_PLURAL_NOT_PRESENT
	AC_PM_RUNTIME_GET_IF_ACTIVE_ARG2_NOT_PRESENT
	AC_COREDUMPM_TIMEOUT_NOT_PRESENT
	AC_DEVCOREDUMP_PUT_NOT_PRESENT
	AC_DRM_BUDDY_FREE_LIST_ARG3_NOT_PRESENT
	AC_DRM_DBG_PRINTER_NOT_PRESENT
	AC_DRM_BUDDY_BLOCK_TRIM_2ND_ARG_NOT_PRESENT
	AC_STR_UP_DOWN_NOT_PRESENT
	AC_FOP_UNSIGNED_OFFSET_NOT_PRESENT
	AC_DRM_LINE_PRINTER_NOT_PRESENT
	AC_STRUCT_DRM_PRINTER_ORIGIN_NOT_PRESENT
	AC_DRM_DBG_RATELIMITED_NOT_PRESENT
	AC_SHRINKER_ALLOC_NOT_PRESENT
	AC_DRM_EXEC_INIT_ARG3_NOT_PRESENT
	AC_SECS_TO_JIFFIES_NOT_PRESENT
	AC_DRMM_CGROUP_REGISTER_REGION_NOT_PRESENT
	AC_PMU_SCOPE_MEMBER_NOT_PRESENT
	AC_PCI_IOV_VF_BAR_FUNCTIONS_NOT_PRESENT
	AC_DRM_GPUVM_RENAMING_SYMBOLS
	AC_DRV_DATE_NOT_PRESENT
	AC_ALLOC_ORDERED_WORKQUEUE_LOCKDEP_MAP_NOT_PRESENT
	AC_CONST_STRUCT_BIN_ATTRIBUTE_IS_NOT_PRESENT
	AC_STRUCT_BIN_ATTRIBUTE_READ_NEW_NOT_PRESENT

dnl # Macros to check for header availability
	AC_KERNEL_CHECK_HEADERS([drm/i915_gsc_proxy_mei_interface.h])
	AC_KERNEL_CHECK_HEADERS([drm/i915_component.h])
	AC_KERNEL_CHECK_HEADERS([drm/intel/i915_drm.h])
	AC_KERNEL_CHECK_HEADERS([linux/wordpart.h])
	AC_KERNEL_CHECK_HEADERS([linux/workqueue_types.h])

	AC_KERNEL_WAIT
])
