#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_BP_MODULES 1
#define CPTCFG_DRM_XE_MODULE 1
#define CPTCFG_DRM_XE_FORCE_PROBE ""
#define CPTCFG_PRELIM_DRM_XE_EUDEBUG 1
#define CPTCFG_DRM_XE_DEBUG 1
#define CPTCFG_DRM_XE_JOB_TIMEOUT_MAX 10000
#define CPTCFG_DRM_XE_JOB_TIMEOUT_MIN 1
#define CPTCFG_DRM_XE_TIMESLICE_MAX 10000000
#define CPTCFG_DRM_XE_TIMESLICE_MIN 1
#define CPTCFG_DRM_XE_PREEMPT_TIMEOUT 640000
#define CPTCFG_DRM_XE_PREEMPT_TIMEOUT_MAX 10000000
#define CPTCFG_DRM_XE_PREEMPT_TIMEOUT_MIN 1
#define CPTCFG_DRM_XE_ENABLE_SCHEDTIMEOUT_LIMIT 1
#define CPTCFG_MTD_INTEL_DG_MODULE 1
#define CPTCFG_INTEL_PMT_CLASS_MODULE 1
#define CPTCFG_INTEL_PMT_TELEMETRY_MODULE 1
#define CPTCFG_INTEL_PMT_CRASHLOG_MODULE 1
#define CPTCFG_INTEL_PMT_DISCOVERY_MODULE 1
#define CPTCFG_XE_VFIO_PCI_MODULE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
