name: BAT Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Queued:
    runs-on: lgci-runner

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Queue testing
        run: |
          COMMIT=$(git rev-parse HEAD^2)
          curl -X POST ${{ secrets.SERVER_URL }} --user ${{ secrets.USER }}:${{ secrets.TOKEN }} --data-urlencode "TARGET_COMMIT=$COMMIT" --data-urlencode "DEBUG=false"
